language: generic

sudo: false

install:
  - git clone --depth=1 https://github.com/thinca/vim-themis /tmp/themis
  - git clone https://github.com/vim/vim $HOME/vim
  - (if ! test -d $HOME/vim-8.0.0000/bin; then cd $HOME/vim && git checkout . && git checkout v8.0.0000 && ./configure --prefix=$HOME/vim-8.0.0000 && make && make install; fi)
  - (if ! test -d $HOME/vim-7.4.1151/bin; then cd $HOME/vim && git checkout . && git checkout v7.4.1151 && ./configure --prefix=$HOME/vim-7.4.1151 && make && make install; fi)

cache:
  directories:
    - $HOME/vim-8.0.0000
    - $HOME/vim-7.4.1151

env:
  - PATH=$HOME/vim-8.0.0000/bin/:$PATH
  - PATH=$HOME/vim-7.4.1151/bin/:$PATH

script:
  - /tmp/themis/bin/themis
